void initialization();
void lcd_print_str(char *p);
void lcd_print_int(int n);
void lcd_print_str_row(char *p,int row);
void lcd_print_int_row(int n,int row);
void lcd_clear();
char keypad_input();
int pushed_key();
void pop_count_down();
void beef_count_down();
void chicken_count_down();
void start_cooking();
void stop_cooking();
void delay_sec(int t);
void delay_ms(int t);
